#!/usr/bin/env python3
"""Installer for the CDISC Concept Curation app.

Run this after extracting the release archive - no git required. Creates a
virtual environment, installs dependencies, collects your CDISC API key,
sets up the database, and creates a double-click "Start" launcher.

    python3 install.py        (Mac/Linux)
    python install.py         (Windows)

Or just double-click "Install (Mac).command" / "Install (Windows).bat" /
run ./install.sh, which call this script for you.
"""

import platform
import secrets
import subprocess
import sys
from pathlib import Path

MIN_PYTHON = (3, 11)
MAX_PYTHON_EXCLUSIVE = (3, 13)  # 3.13+: some deps (e.g. pandas==2.2.2) have no installable package yet
REPO_ROOT = Path(__file__).resolve().parent
VENV_DIR = REPO_ROOT / ".venv"
ENV_FILE = REPO_ROOT / ".env"
ALIGNMENT_DIR = REPO_ROOT / "cdisc-bc-ncit-alignment"


def banner(text):
    print(f"\n== {text} ==")


def fail(message):
    print(f"\nERROR: {message}", file=sys.stderr)
    sys.exit(1)


def check_python_version():
    if sys.version_info < MIN_PYTHON or sys.version_info >= MAX_PYTHON_EXCLUSIVE:
        fail(
            "Python 3.11 or 3.12 is required, found "
            f"{platform.python_version()}. Other versions aren't supported yet "
            "because some dependencies (e.g. pandas) don't have installable "
            "packages for them on every platform. Install Python 3.12 from "
            "https://www.python.org/downloads/ and run this installer again "
            "with that version (on Windows, if you have multiple Python "
            "versions installed, try: py -3.12 install.py)."
        )


def venv_python_path():
    if platform.system() == "Windows":
        return VENV_DIR / "Scripts" / "python.exe"
    return VENV_DIR / "bin" / "python"


def create_venv():
    if VENV_DIR.exists():
        print(f"Using existing virtual environment at {VENV_DIR}")
        return
    banner("Creating virtual environment")
    result = subprocess.run([sys.executable, "-m", "venv", str(VENV_DIR)])
    if result.returncode != 0:
        fail("Failed to create the virtual environment (.venv).")


def install_dependencies():
    banner("Installing dependencies (this can take a few minutes)")
    venv_python = str(venv_python_path())
    steps = [
        [venv_python, "-m", "pip", "install", "--upgrade", "pip"],
        [venv_python, "-m", "pip", "install", "-r", str(REPO_ROOT / "requirements.txt")],
    ]
    for cmd in steps:
        result = subprocess.run(cmd, cwd=REPO_ROOT)
        if result.returncode != 0:
            fail("Failed to install dependencies. Check your internet connection and re-run this installer.")


def check_alignment_submodule():
    if not ALIGNMENT_DIR.exists() or not any(ALIGNMENT_DIR.iterdir()):
        print(
            "\nWARNING: cdisc-bc-ncit-alignment/ is missing or empty. The NCIt "
            "alignment feature will not work, but the rest of the app will install "
            "normally. If this is unexpected, re-download the release archive."
        )


def create_instance_dir():
    (REPO_ROOT / "instance").mkdir(exist_ok=True)


def prompt(message, required=False):
    while True:
        value = input(f"{message}: ").strip()
        if not value and required:
            print("This value is required.")
            continue
        return value


def prompt_yes_no(message, default=False):
    suffix = "Y/n" if default else "y/N"
    value = input(f"{message} [{suffix}]: ").strip().lower()
    if not value:
        return default
    return value in ("y", "yes")


def read_existing_env_value(key):
    if not ENV_FILE.exists():
        return None
    for line in ENV_FILE.read_text().splitlines():
        if line.startswith(f"{key}="):
            return line.split("=", 1)[1]
    return None


def write_env_file():
    if ENV_FILE.exists():
        if prompt_yes_no(f"\n{ENV_FILE.name} already exists. Keep it as-is?", default=True):
            print("Keeping existing .env.")
            return

    banner("Configuration")
    print("Your CDISC API key is required to talk to the CDISC Library.")
    api_key = prompt("CDISC API key", required=True)

    loinc_user = loinc_password = ""
    if prompt_yes_no("Configure LOINC search credentials? (optional)", default=False):
        loinc_user = prompt("LOINC username", required=True)
        loinc_password = prompt("LOINC password", required=True)

    secret_key = secrets.token_hex(32)

    lines = [
        "# Generated by install.py",
        f"CDISC_API_KEY={api_key}",
        f"SECRET_KEY={secret_key}",
        "PORT=8081",
        "FLASK_DEBUG=0",
    ]
    if loinc_user:
        lines.append(f"LOINC_USER={loinc_user}")
        lines.append(f"LOINC_PASSWORD={loinc_password}")
    lines += [
        "",
        "# Optional overrides - uncomment to use:",
        "# CDISC_SUBSCRIPTION_KEY=",
        "# DATABASE_URL=sqlite:///cdisc_curation.db",
        "# ALIGNMENT_SUBMODULE_DIR=",
    ]
    ENV_FILE.write_text("\n".join(lines) + "\n")
    print(f"Wrote {ENV_FILE}")


def bootstrap_database():
    banner("Setting up the database")
    venv_python = str(venv_python_path())
    snippet = "from app import create_app\nfrom db_bootstrap import ensure_db\napp = create_app()\nensure_db(app)\n"
    result = subprocess.run([venv_python, "-c", snippet], cwd=REPO_ROOT)
    if result.returncode != 0:
        fail("Failed to set up the database. See the error above.")


def create_start_launcher():
    banner("Creating a Start launcher")
    port = read_existing_env_value("PORT") or "8081"
    system = platform.system()

    if system == "Windows":
        path = REPO_ROOT / "Start.bat"
        path.write_text(
            "@echo off\r\n"
            'cd /d "%~dp0"\r\n'
            "call .venv\\Scripts\\activate.bat\r\n"
            'start "" powershell -NoProfile -Command '
            f"\"Start-Sleep -Seconds 2; Start-Process 'http://localhost:{port}'\"\r\n"
            "python app.py\r\n"
            "pause\r\n"
        )
    elif system == "Darwin":
        path = REPO_ROOT / "Start.command"
        path.write_text("#!/bin/bash\n" 'cd "$(dirname "$0")"\n' "source .venv/bin/activate\n" f"(sleep 2 && open http://localhost:{port}) &\n" "python app.py\n")
        path.chmod(path.stat().st_mode | 0o111)
    else:
        path = REPO_ROOT / "start.sh"
        path.write_text(
            "#!/bin/bash\n" 'cd "$(dirname "$0")"\n' "source .venv/bin/activate\n" f"command -v xdg-open >/dev/null 2>&1 && (sleep 2 && xdg-open http://localhost:{port}) &\n" "python app.py\n"
        )
        path.chmod(path.stat().st_mode | 0o111)

    print(f"Created {path.name} - double-click it any time to start the app.")
    return path


def main():
    print("CDISC Concept Curation - Installer")
    check_python_version()
    create_venv()
    install_dependencies()
    check_alignment_submodule()
    create_instance_dir()
    write_env_file()
    bootstrap_database()
    launcher = create_start_launcher()

    port = read_existing_env_value("PORT") or "8081"
    banner("Done")
    print(f"Install complete. Double-click {launcher.name} to start the app,")
    print(f"then open http://localhost:{port} in your browser (it should open automatically).")


if __name__ == "__main__":
    main()
