"""baseline: initial schema

Revision ID: 51d4a009d291
Revises:
Create Date: 2026-07-08 15:00:19.432521

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "51d4a009d291"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "audit_logs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("entity_type", sa.String(length=50), nullable=True),
        sa.Column("entity_id", sa.String(length=100), nullable=True),
        sa.Column("action", sa.String(length=100), nullable=True),
        sa.Column("actor", sa.String(length=100), nullable=True),
        sa.Column("before_state", sa.Text(), nullable=True),
        sa.Column("after_state", sa.Text(), nullable=True),
        sa.Column("timestamp", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "biomedical_concepts",
        sa.Column("bc_id", sa.String(length=50), nullable=False),
        sa.Column("short_name", sa.String(length=255), nullable=False),
        sa.Column("definition", sa.Text(), nullable=True),
        sa.Column("ncit_code", sa.String(length=50), nullable=True),
        sa.Column("parent_bc_id", sa.String(length=50), nullable=True),
        sa.Column("bc_categories", sa.String(length=500), nullable=True),
        sa.Column("synonyms", sa.Text(), nullable=True),
        sa.Column("result_scales", sa.String(length=255), nullable=True),
        sa.Column("system", sa.String(length=255), nullable=True),
        sa.Column("system_name", sa.String(length=100), nullable=True),
        sa.Column("loinc_code", sa.String(length=50), nullable=True),
        sa.Column("code", sa.String(length=50), nullable=True),
        sa.Column("loinc_metadata", sa.Text(), nullable=True),
        sa.Column("ncit_metadata", sa.Text(), nullable=True),
        sa.Column("package_date", sa.String(length=20), nullable=True),
        sa.Column("status", sa.String(length=50), nullable=True),
        sa.Column("submitter", sa.String(length=100), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("history_of_change", sa.Text(), nullable=True),
        sa.Column("source", sa.String(length=50), nullable=True),
        sa.ForeignKeyConstraint(
            ["parent_bc_id"],
            ["biomedical_concepts.bc_id"],
        ),
        sa.PrimaryKeyConstraint("bc_id"),
    )
    op.create_table(
        "ingestion_records",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("session_key", sa.String(length=64), nullable=True),
        sa.Column("source_file", sa.String(length=255), nullable=True),
        sa.Column("source_sheet", sa.String(length=100), nullable=True),
        sa.Column("mapped", sa.Text(), nullable=True),
        sa.Column("confidences", sa.Text(), nullable=True),
        sa.Column("errors", sa.Text(), nullable=True),
        sa.Column("decs", sa.Text(), nullable=True),
        sa.Column("duplicate", sa.Boolean(), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("ingestion_records", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_ingestion_records_session_key"), ["session_key"], unique=False)

    op.create_table(
        "data_element_concepts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("dec_id", sa.String(length=50), nullable=False),
        sa.Column("bc_id", sa.String(length=50), nullable=False),
        sa.Column("ncit_dec_code", sa.String(length=50), nullable=True),
        sa.Column("dec_label", sa.String(length=255), nullable=True),
        sa.Column("data_type", sa.String(length=50), nullable=True),
        sa.Column("example_set", sa.Text(), nullable=True),
        sa.Column("required", sa.Boolean(), nullable=True),
        sa.Column("generic_dec", sa.Boolean(), nullable=True),
        sa.Column("template_type", sa.String(length=100), nullable=True),
        sa.Column("sort_order", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["bc_id"],
            ["biomedical_concepts.bc_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "dataset_specializations",
        sa.Column("vlm_group_id", sa.String(length=100), nullable=False),
        sa.Column("bc_id", sa.String(length=50), nullable=False),
        sa.Column("domain", sa.String(length=20), nullable=True),
        sa.Column("short_name", sa.String(length=255), nullable=True),
        sa.Column("variables", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["bc_id"],
            ["biomedical_concepts.bc_id"],
        ),
        sa.PrimaryKeyConstraint("vlm_group_id"),
    )
    op.create_table(
        "governance_records",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("bc_id", sa.String(length=50), nullable=False),
        sa.Column("stage", sa.Integer(), nullable=True),
        sa.Column("action", sa.String(length=100), nullable=True),
        sa.Column("actor", sa.String(length=100), nullable=True),
        sa.Column("comment", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["bc_id"],
            ["biomedical_concepts.bc_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("governance_records")
    op.drop_table("dataset_specializations")
    op.drop_table("data_element_concepts")
    with op.batch_alter_table("ingestion_records", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_ingestion_records_session_key"))

    op.drop_table("ingestion_records")
    op.drop_table("biomedical_concepts")
    op.drop_table("audit_logs")
    # ### end Alembic commands ###
