"""add ncit_metadata to biomedical_concept

Revision ID: b9ee22a174fe
Revises: f27a606163b0
Create Date: 2026-04-08 13:12:22.755530

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b9ee22a174fe'
down_revision = 'f27a606163b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('biomedical_concepts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ncit_metadata', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('biomedical_concepts', schema=None) as batch_op:
        batch_op.drop_column('ncit_metadata')

    # ### end Alembic commands ###
