"""add loinc_metadata to biomedical_concept

Revision ID: f27a606163b0
Revises: 
Create Date: 2026-04-08 12:28:59.039371

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f27a606163b0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('biomedical_concepts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('loinc_metadata', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('biomedical_concepts', schema=None) as batch_op:
        batch_op.drop_column('loinc_metadata')

    # ### end Alembic commands ###
